# <auto-generated by typra-emitter>
##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

import copy
from abc import ABC
from dataclasses import dataclass, field
from typing import Any, ClassVar

from ._Inline import Inline
from ._TableRow import TableRow
from ._context import LoadContext, SaveContext


@dataclass
class Block(ABC):
    """

    Attributes
    ----------
    kind : str

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="")
    _raw: dict[str, Any] = field(default_factory=dict, init=False, repr=False)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "Block":
        """Load a Block instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            Block: The loaded Block instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for Block: {data}")

        # load polymorphic Block instance
        instance = Block.load_kind(data, context)

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if context is not None:
            instance = context.process_output(instance)
        return instance

    @staticmethod
    def load_kind(data: dict, context: LoadContext | None) -> "Block":
        # load polymorphic Block instance
        discriminator_raw = data.get("kind") if data is not None else None
        if not isinstance(discriminator_raw, str) or discriminator_raw == "":
            raise ValueError(
                "Invalid Block discriminator field 'kind': expected non-blank string"
            )
        discriminator_value = discriminator_raw
        if discriminator_value == "heading":
            return Heading.load(data, context)
        elif discriminator_value == "paragraph":
            return Paragraph.load(data, context)
        elif discriminator_value == "code_block":
            return CodeBlock.load(data, context)
        elif discriminator_value == "block_quote":
            return BlockQuote.load(data, context)
        elif discriminator_value == "list_item":
            return ListItemBlock.load(data, context)
        elif discriminator_value == "list":
            return ListBlock.load(data, context)
        elif discriminator_value == "table":
            return TableBlock.load(data, context)
        elif discriminator_value == "thematic_break":
            return ThematicBreak.load(data, context)

        else:
            # absorb unrecognized discriminator
            return UnknownBlock.load(data, context)

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the Block instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        result: dict[str, Any] = copy.deepcopy(obj._raw)

        if obj.kind is not None:
            result["kind"] = obj.kind

        if context is not None:
            result = context.process_dict(result)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the Block instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the Block instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class UnknownBlock(Block):
    """Carries a Block whose discriminator matches no known subtype.

    The unrecognized value stays on `kind` and every key the
    schema does not declare is preserved verbatim, so an unknown Block
    survives a load/save round-trip unchanged.

    """

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "UnknownBlock":
        instance = UnknownBlock()
        instance._raw = copy.deepcopy(data)
        instance._raw.pop("kind", None)
        return instance


@dataclass
class Heading(Block):
    """

    Attributes
    ----------
    kind : str

    level : Any

    content : list[Inline]

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="heading")
    level: Any = field(default=None)
    content: list[Inline] = field(default_factory=list)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "Heading":
        """Load a Heading instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            Heading: The loaded Heading instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for Heading: {data}")

        # create new instance
        instance = Heading()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "level" in data:
            instance.level = data["level"]
        if data is not None and "content" in data:
            instance.content = Heading.load_content(
                data["content"], context.at("content")
            )
        if context is not None:
            instance = context.process_output(instance)
        return instance

    @staticmethod
    def load_content(data: dict | list, context: LoadContext | None) -> list[Inline]:
        if context is None:
            context = LoadContext(path="content")
        if isinstance(data, dict):
            # convert simple named content to list of Inline
            result = []
            for k, v in data.items():
                if isinstance(v, list):
                    raise TypeError(
                        f"{context.at(k).path}: invalid named collection entry category array"
                    )
                if isinstance(v, dict):
                    # value is an object, spread its properties
                    result.append(Inline.load({"name": k, **v}, context.at(k)))
                else:
                    # value is a scalar, use it as the primary property
                    result.append(Inline.load({"name": k, "kind": v}, context.at(k)))
            return result
        return [
            Inline.load(item, context.at_index(index))
            for index, item in enumerate(data)
        ]

    @staticmethod
    def save_content(
        items: list[Inline], context: SaveContext | None
    ) -> dict[str, Any] | list[dict[str, Any]]:
        if context is None:
            context = SaveContext()

        # The schema declares an ordered collection, so preserve array format
        return [item.save(context) for item in items]

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the Heading instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.level is not None:
            result["level"] = obj.level
        if obj.content is not None:
            result["content"] = Heading.save_content(obj.content, context)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the Heading instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the Heading instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class Paragraph(Block):
    """

    Attributes
    ----------
    kind : str

    content : list[Inline]

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="paragraph")
    content: list[Inline] = field(default_factory=list)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "Paragraph":
        """Load a Paragraph instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            Paragraph: The loaded Paragraph instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for Paragraph: {data}")

        # create new instance
        instance = Paragraph()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "content" in data:
            instance.content = Paragraph.load_content(
                data["content"], context.at("content")
            )
        if context is not None:
            instance = context.process_output(instance)
        return instance

    @staticmethod
    def load_content(data: dict | list, context: LoadContext | None) -> list[Inline]:
        if context is None:
            context = LoadContext(path="content")
        if isinstance(data, dict):
            # convert simple named content to list of Inline
            result = []
            for k, v in data.items():
                if isinstance(v, list):
                    raise TypeError(
                        f"{context.at(k).path}: invalid named collection entry category array"
                    )
                if isinstance(v, dict):
                    # value is an object, spread its properties
                    result.append(Inline.load({"name": k, **v}, context.at(k)))
                else:
                    # value is a scalar, use it as the primary property
                    result.append(Inline.load({"name": k, "kind": v}, context.at(k)))
            return result
        return [
            Inline.load(item, context.at_index(index))
            for index, item in enumerate(data)
        ]

    @staticmethod
    def save_content(
        items: list[Inline], context: SaveContext | None
    ) -> dict[str, Any] | list[dict[str, Any]]:
        if context is None:
            context = SaveContext()

        # The schema declares an ordered collection, so preserve array format
        return [item.save(context) for item in items]

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the Paragraph instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.content is not None:
            result["content"] = Paragraph.save_content(obj.content, context)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the Paragraph instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the Paragraph instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class CodeBlock(Block):
    """

    Attributes
    ----------
    kind : str

    language : Optional[str]

    code : str

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="code_block")
    language: str | None = None
    code: str = field(default="")

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "CodeBlock":
        """Load a CodeBlock instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            CodeBlock: The loaded CodeBlock instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for CodeBlock: {data}")

        # create new instance
        instance = CodeBlock()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "language" in data:
            instance.language = data["language"]
        if data is not None and "code" in data:
            instance.code = data["code"]
        if context is not None:
            instance = context.process_output(instance)
        return instance

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the CodeBlock instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.language is not None:
            result["language"] = obj.language
        if obj.code is not None:
            result["code"] = obj.code
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the CodeBlock instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the CodeBlock instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class BlockQuote(Block):
    """

    Attributes
    ----------
    kind : str

    blocks : list[Block]

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="block_quote")
    blocks: list[Block] = field(default_factory=list)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "BlockQuote":
        """Load a BlockQuote instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            BlockQuote: The loaded BlockQuote instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for BlockQuote: {data}")

        # create new instance
        instance = BlockQuote()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "blocks" in data:
            instance.blocks = BlockQuote.load_blocks(
                data["blocks"], context.at("blocks")
            )
        if context is not None:
            instance = context.process_output(instance)
        return instance

    @staticmethod
    def load_blocks(data: dict | list, context: LoadContext | None) -> list[Block]:
        if context is None:
            context = LoadContext(path="blocks")
        if isinstance(data, dict):
            # convert simple named blocks to list of Block
            result = []
            for k, v in data.items():
                if isinstance(v, list):
                    raise TypeError(
                        f"{context.at(k).path}: invalid named collection entry category array"
                    )
                if isinstance(v, dict):
                    # value is an object, spread its properties
                    result.append(Block.load({"name": k, **v}, context.at(k)))
                else:
                    # value is a scalar, use it as the primary property
                    result.append(Block.load({"name": k, "kind": v}, context.at(k)))
            return result
        return [
            Block.load(item, context.at_index(index)) for index, item in enumerate(data)
        ]

    @staticmethod
    def save_blocks(
        items: list[Block], context: SaveContext | None
    ) -> dict[str, Any] | list[dict[str, Any]]:
        if context is None:
            context = SaveContext()

        # The schema declares an ordered collection, so preserve array format
        return [item.save(context) for item in items]

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the BlockQuote instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.blocks is not None:
            result["blocks"] = BlockQuote.save_blocks(obj.blocks, context)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the BlockQuote instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the BlockQuote instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class ListItemBlock(Block):
    """

    Attributes
    ----------
    kind : str

    blocks : list[Block]

    task : Optional[bool]

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="list_item")
    blocks: list[Block] = field(default_factory=list)
    task: bool | None = None

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "ListItemBlock":
        """Load a ListItemBlock instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            ListItemBlock: The loaded ListItemBlock instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for ListItemBlock: {data}")

        # create new instance
        instance = ListItemBlock()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "blocks" in data:
            instance.blocks = ListItemBlock.load_blocks(
                data["blocks"], context.at("blocks")
            )
        if data is not None and "task" in data:
            instance.task = data["task"]
        if context is not None:
            instance = context.process_output(instance)
        return instance

    @staticmethod
    def load_blocks(data: dict | list, context: LoadContext | None) -> list[Block]:
        if context is None:
            context = LoadContext(path="blocks")
        if isinstance(data, dict):
            # convert simple named blocks to list of Block
            result = []
            for k, v in data.items():
                if isinstance(v, list):
                    raise TypeError(
                        f"{context.at(k).path}: invalid named collection entry category array"
                    )
                if isinstance(v, dict):
                    # value is an object, spread its properties
                    result.append(Block.load({"name": k, **v}, context.at(k)))
                else:
                    # value is a scalar, use it as the primary property
                    result.append(Block.load({"name": k, "kind": v}, context.at(k)))
            return result
        return [
            Block.load(item, context.at_index(index)) for index, item in enumerate(data)
        ]

    @staticmethod
    def save_blocks(
        items: list[Block], context: SaveContext | None
    ) -> dict[str, Any] | list[dict[str, Any]]:
        if context is None:
            context = SaveContext()

        # The schema declares an ordered collection, so preserve array format
        return [item.save(context) for item in items]

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the ListItemBlock instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.blocks is not None:
            result["blocks"] = ListItemBlock.save_blocks(obj.blocks, context)
        if obj.task is not None:
            result["task"] = obj.task
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the ListItemBlock instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the ListItemBlock instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class ListBlock(Block):
    """

    Attributes
    ----------
    kind : str

    ordered : bool

    start : Any

    items : list[ListItemBlock]

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="list")
    ordered: bool = field(default=False)
    start: Any = field(default=None)
    items: list[ListItemBlock] = field(default_factory=list)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "ListBlock":
        """Load a ListBlock instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            ListBlock: The loaded ListBlock instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for ListBlock: {data}")

        # create new instance
        instance = ListBlock()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "ordered" in data:
            instance.ordered = data["ordered"]
        if data is not None and "start" in data:
            instance.start = data["start"]
        if data is not None and "items" in data:
            instance.items = ListBlock.load_items(data["items"], context.at("items"))
        if context is not None:
            instance = context.process_output(instance)
        return instance

    @staticmethod
    def load_items(
        data: dict | list, context: LoadContext | None
    ) -> list[ListItemBlock]:
        if context is None:
            context = LoadContext(path="items")
        if isinstance(data, dict):
            # convert simple named items to list of ListItemBlock
            result = []
            for k, v in data.items():
                if isinstance(v, list):
                    raise TypeError(
                        f"{context.at(k).path}: invalid named collection entry category array"
                    )
                if isinstance(v, dict):
                    # value is an object, spread its properties
                    result.append(ListItemBlock.load({"name": k, **v}, context.at(k)))
                else:
                    # value is a scalar, use it as the primary property
                    result.append(
                        ListItemBlock.load({"name": k, "kind": v}, context.at(k))
                    )
            return result
        return [
            ListItemBlock.load(item, context.at_index(index))
            for index, item in enumerate(data)
        ]

    @staticmethod
    def save_items(
        items: list[ListItemBlock], context: SaveContext | None
    ) -> dict[str, Any] | list[dict[str, Any]]:
        if context is None:
            context = SaveContext()

        # The schema declares an ordered collection, so preserve array format
        return [item.save(context) for item in items]

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the ListBlock instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.ordered is not None:
            result["ordered"] = obj.ordered
        if obj.start is not None:
            result["start"] = obj.start
        if obj.items is not None:
            result["items"] = ListBlock.save_items(obj.items, context)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the ListBlock instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the ListBlock instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class TableBlock(Block):
    """

    Attributes
    ----------
    kind : str

    align : list[str]

    head : TableRow

    rows : list[TableRow]

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="table")
    align: list[str] = field(default_factory=list)
    head: TableRow = field(default_factory=TableRow)
    rows: list[TableRow] = field(default_factory=list)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "TableBlock":
        """Load a TableBlock instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            TableBlock: The loaded TableBlock instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for TableBlock: {data}")
        if "head" not in data or data["head"] is None:
            raise ValueError(f"{context.at('head').path}: missing required field")

        # create new instance
        instance = TableBlock()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "align" in data:
            instance.align = data["align"]
        if data is not None and "head" in data:
            instance.head = TableRow.load(data["head"], context.at("head"))
        if data is not None and "rows" in data:
            instance.rows = TableBlock.load_rows(data["rows"], context.at("rows"))
        if context is not None:
            instance = context.process_output(instance)
        return instance

    @staticmethod
    def load_rows(data: dict | list, context: LoadContext | None) -> list[TableRow]:
        if context is None:
            context = LoadContext(path="rows")
        if isinstance(data, dict):
            # convert simple named rows to list of TableRow
            result = []
            for k, v in data.items():
                if isinstance(v, list):
                    raise TypeError(
                        f"{context.at(k).path}: invalid named collection entry category array"
                    )
                if isinstance(v, dict):
                    # value is an object, spread its properties
                    result.append(TableRow.load({"name": k, **v}, context.at(k)))
                else:
                    # value is a scalar, use it as the primary property
                    result.append(TableRow.load({"name": k, "cells": v}, context.at(k)))
            return result
        return [
            TableRow.load(item, context.at_index(index))
            for index, item in enumerate(data)
        ]

    @staticmethod
    def save_rows(
        items: list[TableRow], context: SaveContext | None
    ) -> dict[str, Any] | list[dict[str, Any]]:
        if context is None:
            context = SaveContext()

        # The schema declares an ordered collection, so preserve array format
        return [item.save(context) for item in items]

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the TableBlock instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.align is not None:
            result["align"] = obj.align
        if obj.head is not None:
            result["head"] = obj.head.save(context)
        if obj.rows is not None:
            result["rows"] = TableBlock.save_rows(obj.rows, context)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the TableBlock instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the TableBlock instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class ThematicBreak(Block):
    """

    Attributes
    ----------
    kind : str

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="thematic_break")

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "ThematicBreak":
        """Load a ThematicBreak instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            ThematicBreak: The loaded ThematicBreak instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for ThematicBreak: {data}")

        # create new instance
        instance = ThematicBreak()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if context is not None:
            instance = context.process_output(instance)
        return instance

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the ThematicBreak instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the ThematicBreak instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the ThematicBreak instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)
