# <auto-generated by typra-emitter>
##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from dataclasses import dataclass, field
from typing import Any, ClassVar

from ._Block import Block
from ._context import LoadContext, SaveContext


@dataclass
class FootnoteDefinition:
    """

    Attributes
    ----------
    label : str

    blocks : list[Block]

    """

    _shorthand_property: ClassVar[str | None] = None

    label: str = field(default="")
    blocks: list[Block] = field(default_factory=list)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "FootnoteDefinition":
        """Load a FootnoteDefinition instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            FootnoteDefinition: The loaded FootnoteDefinition instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for FootnoteDefinition: {data}")

        # create new instance
        instance = FootnoteDefinition()

        if data is not None and "label" in data:
            instance.label = data["label"]
        if data is not None and "blocks" in data:
            instance.blocks = FootnoteDefinition.load_blocks(
                data["blocks"], context.at("blocks")
            )
        if context is not None:
            instance = context.process_output(instance)
        return instance

    @staticmethod
    def load_blocks(data: dict | list, context: LoadContext | None) -> list[Block]:
        if context is None:
            context = LoadContext(path="blocks")
        if isinstance(data, dict):
            # convert simple named blocks to list of Block
            result = []
            for k, v in data.items():
                if isinstance(v, list):
                    raise TypeError(
                        f"{context.at(k).path}: invalid named collection entry category array"
                    )
                if isinstance(v, dict):
                    # value is an object, spread its properties
                    result.append(Block.load({"name": k, **v}, context.at(k)))
                else:
                    # value is a scalar, use it as the primary property
                    result.append(Block.load({"name": k, "kind": v}, context.at(k)))
            return result
        return [
            Block.load(item, context.at_index(index)) for index, item in enumerate(data)
        ]

    @staticmethod
    def save_blocks(
        items: list[Block], context: SaveContext | None
    ) -> dict[str, Any] | list[dict[str, Any]]:
        if context is None:
            context = SaveContext()

        # The schema declares an ordered collection, so preserve array format
        return [item.save(context) for item in items]

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the FootnoteDefinition instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        result: dict[str, Any] = {}

        if obj.label is not None:
            result["label"] = obj.label
        if obj.blocks is not None:
            result["blocks"] = FootnoteDefinition.save_blocks(obj.blocks, context)

        if context is not None:
            result = context.process_dict(result)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the FootnoteDefinition instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the FootnoteDefinition instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)
