# <auto-generated by typra-emitter>
##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

import copy
from abc import ABC
from dataclasses import dataclass, field
from typing import Any, ClassVar

from ._context import LoadContext, SaveContext


@dataclass
class Inline(ABC):
    """

    Attributes
    ----------
    kind : str

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="")
    _raw: dict[str, Any] = field(default_factory=dict, init=False, repr=False)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "Inline":
        """Load a Inline instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            Inline: The loaded Inline instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for Inline: {data}")

        # load polymorphic Inline instance
        instance = Inline.load_kind(data, context)

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if context is not None:
            instance = context.process_output(instance)
        return instance

    @staticmethod
    def load_kind(data: dict, context: LoadContext | None) -> "Inline":
        # load polymorphic Inline instance
        discriminator_raw = data.get("kind") if data is not None else None
        if not isinstance(discriminator_raw, str) or discriminator_raw == "":
            raise ValueError(
                "Invalid Inline discriminator field 'kind': expected non-blank string"
            )
        discriminator_value = discriminator_raw
        if discriminator_value == "text":
            return TextInline.load(data, context)
        elif discriminator_value == "strong":
            return StrongInline.load(data, context)
        elif discriminator_value == "emphasis":
            return EmphasisInline.load(data, context)
        elif discriminator_value == "strikethrough":
            return StrikethroughInline.load(data, context)
        elif discriminator_value == "code":
            return CodeInline.load(data, context)
        elif discriminator_value == "link":
            return LinkInline.load(data, context)
        elif discriminator_value == "math":
            return MathInline.load(data, context)
        elif discriminator_value == "image":
            return ImageInline.load(data, context)
        elif discriminator_value == "soft_break":
            return SoftBreakInline.load(data, context)
        elif discriminator_value == "hard_break":
            return HardBreakInline.load(data, context)

        else:
            # absorb unrecognized discriminator
            return UnknownInline.load(data, context)

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the Inline instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        result: dict[str, Any] = copy.deepcopy(obj._raw)

        if obj.kind is not None:
            result["kind"] = obj.kind

        if context is not None:
            result = context.process_dict(result)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the Inline instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the Inline instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class UnknownInline(Inline):
    """Carries a Inline whose discriminator matches no known subtype.

    The unrecognized value stays on `kind` and every key the
    schema does not declare is preserved verbatim, so an unknown Inline
    survives a load/save round-trip unchanged.

    """

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "UnknownInline":
        instance = UnknownInline()
        instance._raw = copy.deepcopy(data)
        instance._raw.pop("kind", None)
        return instance


@dataclass
class TextInline(Inline):
    """

    Attributes
    ----------
    kind : str

    data : str

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="text")
    data: str = field(default="")

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "TextInline":
        """Load a TextInline instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            TextInline: The loaded TextInline instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for TextInline: {data}")

        # create new instance
        instance = TextInline()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "data" in data:
            instance.data = data["data"]
        if context is not None:
            instance = context.process_output(instance)
        return instance

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the TextInline instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.data is not None:
            result["data"] = obj.data
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the TextInline instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the TextInline instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class StrongInline(Inline):
    """

    Attributes
    ----------
    kind : str

    data : list[Inline]

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="strong")
    data: list[Inline] = field(default_factory=list)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "StrongInline":
        """Load a StrongInline instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            StrongInline: The loaded StrongInline instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for StrongInline: {data}")

        # create new instance
        instance = StrongInline()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "data" in data:
            instance.data = StrongInline.load_data(data["data"], context.at("data"))
        if context is not None:
            instance = context.process_output(instance)
        return instance

    @staticmethod
    def load_data(data: dict | list, context: LoadContext | None) -> list[Inline]:
        if context is None:
            context = LoadContext(path="data")
        if isinstance(data, dict):
            # convert simple named data to list of Inline
            result = []
            for k, v in data.items():
                if isinstance(v, list):
                    raise TypeError(
                        f"{context.at(k).path}: invalid named collection entry category array"
                    )
                if isinstance(v, dict):
                    # value is an object, spread its properties
                    result.append(Inline.load({"name": k, **v}, context.at(k)))
                else:
                    # value is a scalar, use it as the primary property
                    result.append(Inline.load({"name": k, "kind": v}, context.at(k)))
            return result
        return [
            Inline.load(item, context.at_index(index))
            for index, item in enumerate(data)
        ]

    @staticmethod
    def save_data(
        items: list[Inline], context: SaveContext | None
    ) -> dict[str, Any] | list[dict[str, Any]]:
        if context is None:
            context = SaveContext()

        # The schema declares an ordered collection, so preserve array format
        return [item.save(context) for item in items]

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the StrongInline instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.data is not None:
            result["data"] = StrongInline.save_data(obj.data, context)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the StrongInline instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the StrongInline instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class EmphasisInline(Inline):
    """

    Attributes
    ----------
    kind : str

    data : list[Inline]

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="emphasis")
    data: list[Inline] = field(default_factory=list)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "EmphasisInline":
        """Load a EmphasisInline instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            EmphasisInline: The loaded EmphasisInline instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for EmphasisInline: {data}")

        # create new instance
        instance = EmphasisInline()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "data" in data:
            instance.data = EmphasisInline.load_data(data["data"], context.at("data"))
        if context is not None:
            instance = context.process_output(instance)
        return instance

    @staticmethod
    def load_data(data: dict | list, context: LoadContext | None) -> list[Inline]:
        if context is None:
            context = LoadContext(path="data")
        if isinstance(data, dict):
            # convert simple named data to list of Inline
            result = []
            for k, v in data.items():
                if isinstance(v, list):
                    raise TypeError(
                        f"{context.at(k).path}: invalid named collection entry category array"
                    )
                if isinstance(v, dict):
                    # value is an object, spread its properties
                    result.append(Inline.load({"name": k, **v}, context.at(k)))
                else:
                    # value is a scalar, use it as the primary property
                    result.append(Inline.load({"name": k, "kind": v}, context.at(k)))
            return result
        return [
            Inline.load(item, context.at_index(index))
            for index, item in enumerate(data)
        ]

    @staticmethod
    def save_data(
        items: list[Inline], context: SaveContext | None
    ) -> dict[str, Any] | list[dict[str, Any]]:
        if context is None:
            context = SaveContext()

        # The schema declares an ordered collection, so preserve array format
        return [item.save(context) for item in items]

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the EmphasisInline instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.data is not None:
            result["data"] = EmphasisInline.save_data(obj.data, context)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the EmphasisInline instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the EmphasisInline instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class StrikethroughInline(Inline):
    """

    Attributes
    ----------
    kind : str

    data : list[Inline]

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="strikethrough")
    data: list[Inline] = field(default_factory=list)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "StrikethroughInline":
        """Load a StrikethroughInline instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            StrikethroughInline: The loaded StrikethroughInline instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for StrikethroughInline: {data}")

        # create new instance
        instance = StrikethroughInline()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "data" in data:
            instance.data = StrikethroughInline.load_data(
                data["data"], context.at("data")
            )
        if context is not None:
            instance = context.process_output(instance)
        return instance

    @staticmethod
    def load_data(data: dict | list, context: LoadContext | None) -> list[Inline]:
        if context is None:
            context = LoadContext(path="data")
        if isinstance(data, dict):
            # convert simple named data to list of Inline
            result = []
            for k, v in data.items():
                if isinstance(v, list):
                    raise TypeError(
                        f"{context.at(k).path}: invalid named collection entry category array"
                    )
                if isinstance(v, dict):
                    # value is an object, spread its properties
                    result.append(Inline.load({"name": k, **v}, context.at(k)))
                else:
                    # value is a scalar, use it as the primary property
                    result.append(Inline.load({"name": k, "kind": v}, context.at(k)))
            return result
        return [
            Inline.load(item, context.at_index(index))
            for index, item in enumerate(data)
        ]

    @staticmethod
    def save_data(
        items: list[Inline], context: SaveContext | None
    ) -> dict[str, Any] | list[dict[str, Any]]:
        if context is None:
            context = SaveContext()

        # The schema declares an ordered collection, so preserve array format
        return [item.save(context) for item in items]

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the StrikethroughInline instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.data is not None:
            result["data"] = StrikethroughInline.save_data(obj.data, context)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the StrikethroughInline instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the StrikethroughInline instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class CodeInline(Inline):
    """

    Attributes
    ----------
    kind : str

    data : str

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="code")
    data: str = field(default="")

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "CodeInline":
        """Load a CodeInline instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            CodeInline: The loaded CodeInline instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for CodeInline: {data}")

        # create new instance
        instance = CodeInline()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "data" in data:
            instance.data = data["data"]
        if context is not None:
            instance = context.process_output(instance)
        return instance

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the CodeInline instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.data is not None:
            result["data"] = obj.data
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the CodeInline instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the CodeInline instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class LinkInline(Inline):
    """

    Attributes
    ----------
    kind : str

    href : str

    content : list[Inline]

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="link")
    href: str = field(default="")
    content: list[Inline] = field(default_factory=list)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "LinkInline":
        """Load a LinkInline instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            LinkInline: The loaded LinkInline instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for LinkInline: {data}")

        # create new instance
        instance = LinkInline()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "href" in data:
            instance.href = data["href"]
        if data is not None and "content" in data:
            instance.content = LinkInline.load_content(
                data["content"], context.at("content")
            )
        if context is not None:
            instance = context.process_output(instance)
        return instance

    @staticmethod
    def load_content(data: dict | list, context: LoadContext | None) -> list[Inline]:
        if context is None:
            context = LoadContext(path="content")
        if isinstance(data, dict):
            # convert simple named content to list of Inline
            result = []
            for k, v in data.items():
                if isinstance(v, list):
                    raise TypeError(
                        f"{context.at(k).path}: invalid named collection entry category array"
                    )
                if isinstance(v, dict):
                    # value is an object, spread its properties
                    result.append(Inline.load({"name": k, **v}, context.at(k)))
                else:
                    # value is a scalar, use it as the primary property
                    result.append(Inline.load({"name": k, "kind": v}, context.at(k)))
            return result
        return [
            Inline.load(item, context.at_index(index))
            for index, item in enumerate(data)
        ]

    @staticmethod
    def save_content(
        items: list[Inline], context: SaveContext | None
    ) -> dict[str, Any] | list[dict[str, Any]]:
        if context is None:
            context = SaveContext()

        # The schema declares an ordered collection, so preserve array format
        return [item.save(context) for item in items]

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the LinkInline instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.href is not None:
            result["href"] = obj.href
        if obj.content is not None:
            result["content"] = LinkInline.save_content(obj.content, context)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the LinkInline instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the LinkInline instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class MathInline(Inline):
    """

    Attributes
    ----------
    kind : str

    latex : str

    display : bool

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="math")
    latex: str = field(default="")
    display: bool = field(default=False)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "MathInline":
        """Load a MathInline instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            MathInline: The loaded MathInline instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for MathInline: {data}")

        # create new instance
        instance = MathInline()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "latex" in data:
            instance.latex = data["latex"]
        if data is not None and "display" in data:
            instance.display = data["display"]
        if context is not None:
            instance = context.process_output(instance)
        return instance

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the MathInline instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.latex is not None:
            result["latex"] = obj.latex
        if obj.display is not None:
            result["display"] = obj.display
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the MathInline instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the MathInline instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class ImageInline(Inline):
    """

    Attributes
    ----------
    kind : str

    src : str

    alt : str

    title : str

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="image")
    src: str = field(default="")
    alt: str = field(default="")
    title: str = field(default="")

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "ImageInline":
        """Load a ImageInline instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            ImageInline: The loaded ImageInline instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for ImageInline: {data}")

        # create new instance
        instance = ImageInline()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if data is not None and "src" in data:
            instance.src = data["src"]
        if data is not None and "alt" in data:
            instance.alt = data["alt"]
        if data is not None and "title" in data:
            instance.title = data["title"]
        if context is not None:
            instance = context.process_output(instance)
        return instance

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the ImageInline instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        if obj.src is not None:
            result["src"] = obj.src
        if obj.alt is not None:
            result["alt"] = obj.alt
        if obj.title is not None:
            result["title"] = obj.title
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the ImageInline instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the ImageInline instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class SoftBreakInline(Inline):
    """

    Attributes
    ----------
    kind : str

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="soft_break")

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "SoftBreakInline":
        """Load a SoftBreakInline instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            SoftBreakInline: The loaded SoftBreakInline instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for SoftBreakInline: {data}")

        # create new instance
        instance = SoftBreakInline()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if context is not None:
            instance = context.process_output(instance)
        return instance

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the SoftBreakInline instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the SoftBreakInline instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the SoftBreakInline instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)


@dataclass
class HardBreakInline(Inline):
    """

    Attributes
    ----------
    kind : str

    """

    _shorthand_property: ClassVar[str | None] = None

    kind: str = field(default="hard_break")

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "HardBreakInline":
        """Load a HardBreakInline instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            HardBreakInline: The loaded HardBreakInline instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for HardBreakInline: {data}")

        # create new instance
        instance = HardBreakInline()

        if data is not None and "kind" in data:
            instance.kind = data["kind"]
        if context is not None:
            instance = context.process_output(instance)
        return instance

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the HardBreakInline instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        # Start with parent class properties
        result = super().save(context)

        if obj.kind is not None:
            result["kind"] = obj.kind
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the HardBreakInline instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the HardBreakInline instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)
