# <auto-generated by typra-emitter>
##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from typing import Protocol, runtime_checkable

from ._ConvertOptions import ConvertOptions
from ._Document import Document
from ._RenderOptions import RenderOptions
from ._RenderStats import RenderStats


@runtime_checkable
class Quilldown(Protocol):
    def emit(self, doc: Document, options: RenderOptions | None) -> RenderStats:
        raise NotImplementedError

    async def emit_async(
        self, doc: Document, options: RenderOptions | None
    ) -> RenderStats:
        raise NotImplementedError

    def lower(self, markdown: str, options: ConvertOptions | None) -> Document:
        raise NotImplementedError

    async def lower_async(
        self, markdown: str, options: ConvertOptions | None
    ) -> Document:
        raise NotImplementedError
