# <auto-generated by typra-emitter>
##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from dataclasses import dataclass
from typing import Any, ClassVar

from ._context import LoadContext, SaveContext


@dataclass
class RenderOptions:
    """

    Attributes
    ----------
    strict : Optional[bool]

    theme : Optional[str]

    page_size : Optional[str]

    orientation : Optional[str]

    margin : Optional[float]

    page_numbers : Optional[bool]

    table_of_contents : Optional[bool]

    captions : Optional[bool]

    """

    _shorthand_property: ClassVar[str | None] = None

    strict: bool | None = None
    theme: str | None = None
    page_size: str | None = None
    orientation: str | None = None
    margin: float | None = None
    page_numbers: bool | None = None
    table_of_contents: bool | None = None
    captions: bool | None = None

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "RenderOptions":
        """Load a RenderOptions instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            RenderOptions: The loaded RenderOptions instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for RenderOptions: {data}")

        # create new instance
        instance = RenderOptions()

        if data is not None and "strict" in data:
            instance.strict = data["strict"]
        if data is not None and "theme" in data:
            instance.theme = data["theme"]
        if data is not None and "page_size" in data:
            instance.page_size = data["page_size"]
        if data is not None and "orientation" in data:
            instance.orientation = data["orientation"]
        if data is not None and "margin" in data:
            instance.margin = data["margin"]
        if data is not None and "page_numbers" in data:
            instance.page_numbers = data["page_numbers"]
        if data is not None and "table_of_contents" in data:
            instance.table_of_contents = data["table_of_contents"]
        if data is not None and "captions" in data:
            instance.captions = data["captions"]
        if context is not None:
            instance = context.process_output(instance)
        return instance

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the RenderOptions instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        result: dict[str, Any] = {}

        if obj.strict is not None:
            result["strict"] = obj.strict
        if obj.theme is not None:
            result["theme"] = obj.theme
        if obj.page_size is not None:
            result["page_size"] = obj.page_size
        if obj.orientation is not None:
            result["orientation"] = obj.orientation
        if obj.margin is not None:
            result["margin"] = obj.margin
        if obj.page_numbers is not None:
            result["page_numbers"] = obj.page_numbers
        if obj.table_of_contents is not None:
            result["table_of_contents"] = obj.table_of_contents
        if obj.captions is not None:
            result["captions"] = obj.captions

        if context is not None:
            result = context.process_dict(result)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the RenderOptions instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the RenderOptions instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)
