# <auto-generated by typra-emitter>
##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from dataclasses import dataclass, field
from typing import Any, ClassVar

from ._context import LoadContext, SaveContext


@dataclass
class RenderStats:
    """

    Attributes
    ----------
    headings : Any

    paragraphs : Any

    code_blocks : Any

    block_quotes : Any

    lists : Any

    list_items : Any

    tables : Any

    links : Any

    thematic_breaks : Any

    warnings : list[str]

    """

    _shorthand_property: ClassVar[str | None] = None

    headings: Any = field(default=None)
    paragraphs: Any = field(default=None)
    code_blocks: Any = field(default=None)
    block_quotes: Any = field(default=None)
    lists: Any = field(default=None)
    list_items: Any = field(default=None)
    tables: Any = field(default=None)
    links: Any = field(default=None)
    thematic_breaks: Any = field(default=None)
    warnings: list[str] = field(default_factory=list)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "RenderStats":
        """Load a RenderStats instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            RenderStats: The loaded RenderStats instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for RenderStats: {data}")

        # create new instance
        instance = RenderStats()

        if data is not None and "headings" in data:
            instance.headings = data["headings"]
        if data is not None and "paragraphs" in data:
            instance.paragraphs = data["paragraphs"]
        if data is not None and "codeBlocks" in data:
            instance.code_blocks = data["codeBlocks"]
        if data is not None and "blockQuotes" in data:
            instance.block_quotes = data["blockQuotes"]
        if data is not None and "lists" in data:
            instance.lists = data["lists"]
        if data is not None and "listItems" in data:
            instance.list_items = data["listItems"]
        if data is not None and "tables" in data:
            instance.tables = data["tables"]
        if data is not None and "links" in data:
            instance.links = data["links"]
        if data is not None and "thematicBreaks" in data:
            instance.thematic_breaks = data["thematicBreaks"]
        if data is not None and "warnings" in data:
            instance.warnings = data["warnings"]
        if context is not None:
            instance = context.process_output(instance)
        return instance

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the RenderStats instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        result: dict[str, Any] = {}

        if obj.headings is not None:
            result["headings"] = obj.headings
        if obj.paragraphs is not None:
            result["paragraphs"] = obj.paragraphs
        if obj.code_blocks is not None:
            result["codeBlocks"] = obj.code_blocks
        if obj.block_quotes is not None:
            result["blockQuotes"] = obj.block_quotes
        if obj.lists is not None:
            result["lists"] = obj.lists
        if obj.list_items is not None:
            result["listItems"] = obj.list_items
        if obj.tables is not None:
            result["tables"] = obj.tables
        if obj.links is not None:
            result["links"] = obj.links
        if obj.thematic_breaks is not None:
            result["thematicBreaks"] = obj.thematic_breaks
        if obj.warnings is not None:
            result["warnings"] = obj.warnings

        if context is not None:
            result = context.process_dict(result)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the RenderStats instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the RenderStats instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)
