# <auto-generated by typra-emitter>
##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from dataclasses import dataclass, field
from typing import ClassVar

from ._Document import Document
from ._context import LoadContext, SaveContext


@dataclass
class Samples:
    """

    Attributes
    ----------
    headings : Document

    paragraph_inline : Document

    external_link : Document

    anchor_link : Document

    ordered_list : Document

    ordered_start : Document

    bullet_list : Document

    task_list : Document

    table : Document

    code_block : Document

    blockquote : Document

    thematic_break : Document

    heading_para : Document

    """

    _shorthand_property: ClassVar[str | None] = None

    headings: Document = field(default_factory=Document)
    paragraph_inline: Document = field(default_factory=Document)
    external_link: Document = field(default_factory=Document)
    anchor_link: Document = field(default_factory=Document)
    ordered_list: Document = field(default_factory=Document)
    ordered_start: Document = field(default_factory=Document)
    bullet_list: Document = field(default_factory=Document)
    task_list: Document = field(default_factory=Document)
    table: Document = field(default_factory=Document)
    code_block: Document = field(default_factory=Document)
    blockquote: Document = field(default_factory=Document)
    thematic_break: Document = field(default_factory=Document)
    heading_para: Document = field(default_factory=Document)
