# <auto-generated by typra-emitter>
##########################################
# WARNING: This is an auto-generated file.
# DO NOT EDIT THIS FILE DIRECTLY
# ANY EDITS WILL BE LOST
##########################################

from dataclasses import dataclass, field
from typing import Any, ClassVar

from ._Inline import Inline
from ._context import LoadContext, SaveContext


@dataclass
class TableCell:
    """

    Attributes
    ----------
    content : list[Inline]

    """

    _shorthand_property: ClassVar[str | None] = None

    content: list[Inline] = field(default_factory=list)

    @staticmethod
    def load(data: Any, context: LoadContext | None = None) -> "TableCell":
        """Load a TableCell instance.
        Args:
            data (Any): The data to load the instance from.
            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.
        Returns:
            TableCell: The loaded TableCell instance.

        """

        if context is None:
            context = LoadContext()
        data = context.process_input(data)

        if not isinstance(data, dict):
            raise ValueError(f"Invalid data for TableCell: {data}")

        # create new instance
        instance = TableCell()

        if data is not None and "content" in data:
            instance.content = TableCell.load_content(
                data["content"], context.at("content")
            )
        if context is not None:
            instance = context.process_output(instance)
        return instance

    @staticmethod
    def load_content(data: dict | list, context: LoadContext | None) -> list[Inline]:
        if context is None:
            context = LoadContext(path="content")
        if isinstance(data, dict):
            # convert simple named content to list of Inline
            result = []
            for k, v in data.items():
                if isinstance(v, list):
                    raise TypeError(
                        f"{context.at(k).path}: invalid named collection entry category array"
                    )
                if isinstance(v, dict):
                    # value is an object, spread its properties
                    result.append(Inline.load({"name": k, **v}, context.at(k)))
                else:
                    # value is a scalar, use it as the primary property
                    result.append(Inline.load({"name": k, "kind": v}, context.at(k)))
            return result
        return [
            Inline.load(item, context.at_index(index))
            for index, item in enumerate(data)
        ]

    @staticmethod
    def save_content(
        items: list[Inline], context: SaveContext | None
    ) -> dict[str, Any] | list[dict[str, Any]]:
        if context is None:
            context = SaveContext()

        # The schema declares an ordered collection, so preserve array format
        return [item.save(context) for item in items]

    def save(self, context: SaveContext | None = None) -> dict[str, Any]:
        """Save the TableCell instance to a dictionary.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            dict[str, Any]: The dictionary representation of this instance.

        """
        obj = self
        if context is not None:
            obj = context.process_object(obj)

        result: dict[str, Any] = {}

        if obj.content is not None:
            result["content"] = TableCell.save_content(obj.content, context)

        if context is not None:
            result = context.process_dict(result)
        return result

    def to_yaml(self, context: SaveContext | None = None) -> str:
        """Convert the TableCell instance to a YAML string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
        Returns:
            str: The YAML string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_yaml(self.save(context))

    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:
        """Convert the TableCell instance to a JSON string.
        Args:
            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.
            indent (int): Number of spaces for indentation. Defaults to 2.
        Returns:
            str: The JSON string representation of this instance.

        """
        if context is None:
            context = SaveContext()
        return context.to_json(self.save(context), indent)
