# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import TableCell


def test_load_json_tablecell():
    json_data = r"""
    {
      "content": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = TableCell.load(data)
    assert instance is not None


def test_load_yaml_tablecell():
    yaml_data = r"""
    content: []

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = TableCell.load(data)
    assert instance is not None


def test_roundtrip_json_tablecell():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "content": []
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = TableCell.load(original_data)
    saved_data = instance.save()
    reloaded = TableCell.load(saved_data)
    assert reloaded is not None


def test_to_json_tablecell():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "content": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = TableCell.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_tablecell():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "content": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = TableCell.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
