# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import Inline


def test_load_json_inline():
    json_data = r"""
    {
      "kind": "text",
      "data": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = Inline.load(data)
    assert instance is not None
    assert instance.kind == "text"


def test_load_yaml_inline():
    yaml_data = r"""
    kind: text
    data: sample

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = Inline.load(data)
    assert instance is not None
    assert instance.kind == "text"


def test_roundtrip_json_inline():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "kind": "text",
      "data": "sample"
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = Inline.load(original_data)
    saved_data = instance.save()
    reloaded = Inline.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "text"


def test_to_json_inline():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "kind": "text",
      "data": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = Inline.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_inline():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "kind": "text",
      "data": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = Inline.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
