# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import StrongInline


def test_load_json_stronginline():
    json_data = r"""
    {
      "kind": "strong",
      "data": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = StrongInline.load(data)
    assert instance is not None
    assert instance.kind == "strong"


def test_load_yaml_stronginline():
    yaml_data = r"""
    kind: strong
    data: []

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = StrongInline.load(data)
    assert instance is not None
    assert instance.kind == "strong"


def test_roundtrip_json_stronginline():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "kind": "strong",
      "data": []
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = StrongInline.load(original_data)
    saved_data = instance.save()
    reloaded = StrongInline.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "strong"


def test_to_json_stronginline():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "kind": "strong",
      "data": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = StrongInline.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_stronginline():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "kind": "strong",
      "data": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = StrongInline.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
