# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import ListItemBlock


def test_load_json_listitemblock():
    json_data = r"""
    {
      "kind": "list_item",
      "blocks": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ListItemBlock.load(data)
    assert instance is not None
    assert instance.kind == "list_item"


def test_load_yaml_listitemblock():
    yaml_data = r"""
    kind: list_item
    blocks: []

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = ListItemBlock.load(data)
    assert instance is not None
    assert instance.kind == "list_item"


def test_roundtrip_json_listitemblock():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "kind": "list_item",
      "blocks": []
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = ListItemBlock.load(original_data)
    saved_data = instance.save()
    reloaded = ListItemBlock.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "list_item"


def test_to_json_listitemblock():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "kind": "list_item",
      "blocks": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ListItemBlock.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_listitemblock():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "kind": "list_item",
      "blocks": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ListItemBlock.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
