# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import CodeInline


def test_load_json_codeinline():
    json_data = r"""
    {
      "kind": "code",
      "data": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = CodeInline.load(data)
    assert instance is not None
    assert instance.kind == "code"
    assert instance.data == "sample"


def test_load_yaml_codeinline():
    yaml_data = r"""
    kind: code
    data: sample

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = CodeInline.load(data)
    assert instance is not None
    assert instance.kind == "code"
    assert instance.data == "sample"


def test_roundtrip_json_codeinline():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "kind": "code",
      "data": "sample"
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = CodeInline.load(original_data)
    saved_data = instance.save()
    reloaded = CodeInline.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "code"
    assert reloaded.data == "sample"


def test_to_json_codeinline():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "kind": "code",
      "data": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = CodeInline.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_codeinline():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "kind": "code",
      "data": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = CodeInline.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
