# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import CodeBlock


def test_load_json_codeblock():
    json_data = r"""
    {
      "kind": "code_block",
      "code": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = CodeBlock.load(data)
    assert instance is not None
    assert instance.kind == "code_block"
    assert instance.code == "sample"


def test_load_yaml_codeblock():
    yaml_data = r"""
    kind: code_block
    code: sample

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = CodeBlock.load(data)
    assert instance is not None
    assert instance.kind == "code_block"
    assert instance.code == "sample"


def test_roundtrip_json_codeblock():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "kind": "code_block",
      "code": "sample"
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = CodeBlock.load(original_data)
    saved_data = instance.save()
    reloaded = CodeBlock.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "code_block"
    assert reloaded.code == "sample"


def test_to_json_codeblock():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "kind": "code_block",
      "code": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = CodeBlock.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_codeblock():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "kind": "code_block",
      "code": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = CodeBlock.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
