# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import LinkInline


def test_load_json_linkinline():
    json_data = r"""
    {
      "kind": "link",
      "href": "sample",
      "content": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = LinkInline.load(data)
    assert instance is not None
    assert instance.kind == "link"
    assert instance.href == "sample"


def test_load_yaml_linkinline():
    yaml_data = r"""
    kind: link
    href: sample
    content: []

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = LinkInline.load(data)
    assert instance is not None
    assert instance.kind == "link"
    assert instance.href == "sample"


def test_roundtrip_json_linkinline():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "kind": "link",
      "href": "sample",
      "content": []
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = LinkInline.load(original_data)
    saved_data = instance.save()
    reloaded = LinkInline.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "link"
    assert reloaded.href == "sample"


def test_to_json_linkinline():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "kind": "link",
      "href": "sample",
      "content": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = LinkInline.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_linkinline():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "kind": "link",
      "href": "sample",
      "content": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = LinkInline.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
