# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import RenderStats


def test_load_json_renderstats():
    json_data = r"""
    {
      "headings": 1,
      "paragraphs": 1,
      "codeBlocks": 1,
      "blockQuotes": 1,
      "lists": 1,
      "listItems": 1,
      "tables": 1,
      "links": 1,
      "thematicBreaks": 1,
      "warnings": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = RenderStats.load(data)
    assert instance is not None
    assert instance.headings == 1
    assert instance.paragraphs == 1
    assert instance.code_blocks == 1
    assert instance.block_quotes == 1
    assert instance.lists == 1
    assert instance.list_items == 1
    assert instance.tables == 1
    assert instance.links == 1
    assert instance.thematic_breaks == 1


def test_load_yaml_renderstats():
    yaml_data = r"""
    headings: 1
    paragraphs: 1
    codeBlocks: 1
    blockQuotes: 1
    lists: 1
    listItems: 1
    tables: 1
    links: 1
    thematicBreaks: 1
    warnings: []

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = RenderStats.load(data)
    assert instance is not None
    assert instance.headings == 1
    assert instance.paragraphs == 1
    assert instance.code_blocks == 1
    assert instance.block_quotes == 1
    assert instance.lists == 1
    assert instance.list_items == 1
    assert instance.tables == 1
    assert instance.links == 1
    assert instance.thematic_breaks == 1


def test_roundtrip_json_renderstats():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "headings": 1,
      "paragraphs": 1,
      "codeBlocks": 1,
      "blockQuotes": 1,
      "lists": 1,
      "listItems": 1,
      "tables": 1,
      "links": 1,
      "thematicBreaks": 1,
      "warnings": []
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = RenderStats.load(original_data)
    saved_data = instance.save()
    reloaded = RenderStats.load(saved_data)
    assert reloaded is not None
    assert reloaded.headings == 1
    assert reloaded.paragraphs == 1
    assert reloaded.code_blocks == 1
    assert reloaded.block_quotes == 1
    assert reloaded.lists == 1
    assert reloaded.list_items == 1
    assert reloaded.tables == 1
    assert reloaded.links == 1
    assert reloaded.thematic_breaks == 1


def test_to_json_renderstats():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "headings": 1,
      "paragraphs": 1,
      "codeBlocks": 1,
      "blockQuotes": 1,
      "lists": 1,
      "listItems": 1,
      "tables": 1,
      "links": 1,
      "thematicBreaks": 1,
      "warnings": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = RenderStats.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_renderstats():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "headings": 1,
      "paragraphs": 1,
      "codeBlocks": 1,
      "blockQuotes": 1,
      "lists": 1,
      "listItems": 1,
      "tables": 1,
      "links": 1,
      "thematicBreaks": 1,
      "warnings": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = RenderStats.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
