# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import MathInline


def test_load_json_mathinline():
    json_data = r"""
    {
      "kind": "math",
      "latex": "sample",
      "display": true
    }
    """
    data = json.loads(json_data, strict=False)
    instance = MathInline.load(data)
    assert instance is not None
    assert instance.kind == "math"
    assert instance.latex == "sample"
    assert instance.display


def test_load_yaml_mathinline():
    yaml_data = r"""
    kind: math
    latex: sample
    display: true

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = MathInline.load(data)
    assert instance is not None
    assert instance.kind == "math"
    assert instance.latex == "sample"
    assert instance.display


def test_roundtrip_json_mathinline():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "kind": "math",
      "latex": "sample",
      "display": true
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = MathInline.load(original_data)
    saved_data = instance.save()
    reloaded = MathInline.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "math"
    assert reloaded.latex == "sample"
    assert reloaded.display


def test_to_json_mathinline():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "kind": "math",
      "latex": "sample",
      "display": true
    }
    """
    data = json.loads(json_data, strict=False)
    instance = MathInline.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_mathinline():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "kind": "math",
      "latex": "sample",
      "display": true
    }
    """
    data = json.loads(json_data, strict=False)
    instance = MathInline.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
