# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import FootnoteReferenceInline


def test_load_json_footnotereferenceinline():
    json_data = r"""
    {
      "kind": "footnote_reference",
      "label": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = FootnoteReferenceInline.load(data)
    assert instance is not None
    assert instance.kind == "footnote_reference"
    assert instance.label == "sample"


def test_load_yaml_footnotereferenceinline():
    yaml_data = r"""
    kind: footnote_reference
    label: sample

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = FootnoteReferenceInline.load(data)
    assert instance is not None
    assert instance.kind == "footnote_reference"
    assert instance.label == "sample"


def test_roundtrip_json_footnotereferenceinline():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "kind": "footnote_reference",
      "label": "sample"
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = FootnoteReferenceInline.load(original_data)
    saved_data = instance.save()
    reloaded = FootnoteReferenceInline.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "footnote_reference"
    assert reloaded.label == "sample"


def test_to_json_footnotereferenceinline():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "kind": "footnote_reference",
      "label": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = FootnoteReferenceInline.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_footnotereferenceinline():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "kind": "footnote_reference",
      "label": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = FootnoteReferenceInline.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
