# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import TableBlock


def test_load_json_tableblock():
    json_data = r"""
    {
      "kind": "table",
      "align": [],
      "head": {
        "cells": []
      },
      "rows": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = TableBlock.load(data)
    assert instance is not None
    assert instance.kind == "table"


def test_load_yaml_tableblock():
    yaml_data = r"""
    kind: table
    align: []
    head:
      cells: []
    rows: []

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = TableBlock.load(data)
    assert instance is not None
    assert instance.kind == "table"


def test_roundtrip_json_tableblock():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "kind": "table",
      "align": [],
      "head": {
        "cells": []
      },
      "rows": []
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = TableBlock.load(original_data)
    saved_data = instance.save()
    reloaded = TableBlock.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "table"


def test_to_json_tableblock():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "kind": "table",
      "align": [],
      "head": {
        "cells": []
      },
      "rows": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = TableBlock.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_tableblock():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "kind": "table",
      "align": [],
      "head": {
        "cells": []
      },
      "rows": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = TableBlock.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
