# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import BlockQuote


def test_load_json_blockquote():
    json_data = r"""
    {
      "kind": "block_quote",
      "blocks": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = BlockQuote.load(data)
    assert instance is not None
    assert instance.kind == "block_quote"


def test_load_yaml_blockquote():
    yaml_data = r"""
    kind: block_quote
    blocks: []

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = BlockQuote.load(data)
    assert instance is not None
    assert instance.kind == "block_quote"


def test_roundtrip_json_blockquote():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "kind": "block_quote",
      "blocks": []
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = BlockQuote.load(original_data)
    saved_data = instance.save()
    reloaded = BlockQuote.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "block_quote"


def test_to_json_blockquote():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "kind": "block_quote",
      "blocks": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = BlockQuote.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_blockquote():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "kind": "block_quote",
      "blocks": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = BlockQuote.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
