# <auto-generated by typra-emitter>
# Copyright (c) Microsoft. All rights reserved.
# WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.
#
# Enforced @vector behavioral conformance. Each vector is replayed through the
# seam-agnostic runner in vector_runner, which is injected with the
# runtime-authored adapter tables resolved from the module referenced by the
# target's 'vector-adapter-path' option. A vector with no adapter and no
# explicit waiver is a hard failure -- this suite never skips silently.
# See docs: reference/vector-conformance.

import importlib
import json
import os

import pytest

from vector_runner import run_vector

# Run every generated test on pytest-asyncio's event loop so awaitable adapters
# are driven the way a real application invokes the runtime.
pytestmark = pytest.mark.asyncio

_ADAPTER_MODULE = importlib.import_module("vector_adapters")
VECTOR_ADAPTERS = getattr(_ADAPTER_MODULE, "VECTOR_ADAPTERS", {})
VECTOR_WAIVERS = getattr(_ADAPTER_MODULE, "VECTOR_WAIVERS", {})
VECTOR_DOUBLES = getattr(_ADAPTER_MODULE, "VECTOR_DOUBLES", {})

_BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Runtime-authored seam injected into the value-independent runner.
_SEAM = {
    "adapters": VECTOR_ADAPTERS,
    "waivers": VECTOR_WAIVERS,
    "doubles": VECTOR_DOUBLES,
    "base_dir": _BASE_DIR,
}


async def test_vector_0_quilldown_emit_anchor_link_emit():
    vector_json = r"""
    {
      "name": "anchor_link-emit",
      "stage": "callable",
      "input": {
        "doc": {
          "blocks": [
            {
              "content": [
                {
                  "data": "Getting Started",
                  "kind": "text"
                }
              ],
              "kind": "heading",
              "level": 1
            },
            {
              "content": [
                {
                  "data": "Jump to ",
                  "kind": "text"
                },
                {
                  "kind": "link",
                  "href": "#getting-started",
                  "content": [
                    {
                      "data": "start",
                      "kind": "text"
                    }
                  ]
                },
                {
                  "data": ".",
                  "kind": "text"
                }
              ],
              "kind": "paragraph"
            }
          ]
        }
      },
      "expected": {
        "headings": 1,
        "paragraphs": 1,
        "codeBlocks": 0,
        "blockQuotes": 0,
        "lists": 0,
        "listItems": 0,
        "tables": 0,
        "links": 1,
        "thematicBreaks": 0,
        "warnings": []
      },
      "operation": "emit"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "emit", vector, False, _SEAM)


async def test_vector_1_quilldown_emit_blockquote_emit():
    vector_json = r"""
    {
      "name": "blockquote-emit",
      "stage": "callable",
      "input": {
        "doc": {
          "blocks": [
            {
              "blocks": [
                {
                  "content": [
                    {
                      "data": "quoted ",
                      "kind": "text"
                    },
                    {
                      "data": [
                        {
                          "data": "text",
                          "kind": "text"
                        }
                      ],
                      "kind": "strong"
                    }
                  ],
                  "kind": "paragraph"
                }
              ],
              "kind": "block_quote"
            }
          ]
        }
      },
      "expected": {
        "headings": 0,
        "paragraphs": 1,
        "codeBlocks": 0,
        "blockQuotes": 1,
        "lists": 0,
        "listItems": 0,
        "tables": 0,
        "links": 0,
        "thematicBreaks": 0,
        "warnings": []
      },
      "operation": "emit"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "emit", vector, False, _SEAM)


async def test_vector_2_quilldown_emit_bullet_list_emit():
    vector_json = r"""
    {
      "name": "bullet_list-emit",
      "stage": "callable",
      "input": {
        "doc": {
          "blocks": [
            {
              "items": [
                {
                  "kind": "list_item",
                  "blocks": [
                    {
                      "content": [
                        {
                          "data": "alpha",
                          "kind": "text"
                        }
                      ],
                      "kind": "paragraph"
                    }
                  ]
                },
                {
                  "kind": "list_item",
                  "blocks": [
                    {
                      "content": [
                        {
                          "data": "beta",
                          "kind": "text"
                        }
                      ],
                      "kind": "paragraph"
                    }
                  ]
                }
              ],
              "kind": "list",
              "ordered": false,
              "start": 1
            }
          ]
        }
      },
      "expected": {
        "headings": 0,
        "paragraphs": 2,
        "codeBlocks": 0,
        "blockQuotes": 0,
        "lists": 1,
        "listItems": 2,
        "tables": 0,
        "links": 0,
        "thematicBreaks": 0,
        "warnings": []
      },
      "operation": "emit"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "emit", vector, False, _SEAM)


async def test_vector_3_quilldown_emit_code_block_emit():
    vector_json = r"""
    {
      "name": "code_block-emit",
      "stage": "callable",
      "input": {
        "doc": {
          "blocks": [
            {
              "code": "fn main() {}\n",
              "kind": "code_block",
              "language": "rust"
            }
          ]
        }
      },
      "expected": {
        "headings": 0,
        "paragraphs": 0,
        "codeBlocks": 1,
        "blockQuotes": 0,
        "lists": 0,
        "listItems": 0,
        "tables": 0,
        "links": 0,
        "thematicBreaks": 0,
        "warnings": []
      },
      "operation": "emit"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "emit", vector, False, _SEAM)


async def test_vector_4_quilldown_emit_external_link_emit():
    vector_json = r"""
    {
      "name": "external_link-emit",
      "stage": "callable",
      "input": {
        "doc": {
          "blocks": [
            {
              "content": [
                {
                  "data": "See the ",
                  "kind": "text"
                },
                {
                  "kind": "link",
                  "href": "https://example.com/guide",
                  "content": [
                    {
                      "data": "manual",
                      "kind": "text"
                    }
                  ]
                },
                {
                  "data": ".",
                  "kind": "text"
                }
              ],
              "kind": "paragraph"
            }
          ]
        }
      },
      "expected": {
        "headings": 0,
        "paragraphs": 1,
        "codeBlocks": 0,
        "blockQuotes": 0,
        "lists": 0,
        "listItems": 0,
        "tables": 0,
        "links": 1,
        "thematicBreaks": 0,
        "warnings": []
      },
      "operation": "emit"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "emit", vector, False, _SEAM)


async def test_vector_5_quilldown_emit_heading_para_emit():
    vector_json = r"""
    {
      "name": "heading_para-emit",
      "stage": "callable",
      "input": {
        "doc": {
          "blocks": [
            {
              "content": [
                {
                  "data": "Title",
                  "kind": "text"
                }
              ],
              "kind": "heading",
              "level": 1
            },
            {
              "content": [
                {
                  "data": "Hello ",
                  "kind": "text"
                },
                {
                  "data": [
                    {
                      "data": "world",
                      "kind": "text"
                    }
                  ],
                  "kind": "strong"
                },
                {
                  "data": ".",
                  "kind": "text"
                }
              ],
              "kind": "paragraph"
            }
          ]
        }
      },
      "expected": {
        "headings": 1,
        "paragraphs": 1,
        "codeBlocks": 0,
        "blockQuotes": 0,
        "lists": 0,
        "listItems": 0,
        "tables": 0,
        "links": 0,
        "thematicBreaks": 0,
        "warnings": []
      },
      "operation": "emit"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "emit", vector, False, _SEAM)


async def test_vector_6_quilldown_emit_headings_emit():
    vector_json = r"""
    {
      "name": "headings-emit",
      "stage": "callable",
      "input": {
        "doc": {
          "blocks": [
            {
              "content": [
                {
                  "data": "One",
                  "kind": "text"
                }
              ],
              "kind": "heading",
              "level": 1
            },
            {
              "content": [
                {
                  "data": "Two",
                  "kind": "text"
                }
              ],
              "kind": "heading",
              "level": 2
            },
            {
              "content": [
                {
                  "data": "Three",
                  "kind": "text"
                }
              ],
              "kind": "heading",
              "level": 3
            }
          ]
        }
      },
      "expected": {
        "headings": 3,
        "paragraphs": 0,
        "codeBlocks": 0,
        "blockQuotes": 0,
        "lists": 0,
        "listItems": 0,
        "tables": 0,
        "links": 0,
        "thematicBreaks": 0,
        "warnings": []
      },
      "operation": "emit"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "emit", vector, False, _SEAM)


async def test_vector_7_quilldown_emit_ordered_list_emit():
    vector_json = r"""
    {
      "name": "ordered_list-emit",
      "stage": "callable",
      "input": {
        "doc": {
          "blocks": [
            {
              "items": [
                {
                  "kind": "list_item",
                  "blocks": [
                    {
                      "content": [
                        {
                          "data": "alpha",
                          "kind": "text"
                        }
                      ],
                      "kind": "paragraph"
                    }
                  ]
                },
                {
                  "kind": "list_item",
                  "blocks": [
                    {
                      "content": [
                        {
                          "data": "beta",
                          "kind": "text"
                        }
                      ],
                      "kind": "paragraph"
                    }
                  ]
                },
                {
                  "kind": "list_item",
                  "blocks": [
                    {
                      "content": [
                        {
                          "data": "gamma",
                          "kind": "text"
                        }
                      ],
                      "kind": "paragraph"
                    }
                  ]
                }
              ],
              "kind": "list",
              "ordered": true,
              "start": 1
            }
          ]
        }
      },
      "expected": {
        "headings": 0,
        "paragraphs": 3,
        "codeBlocks": 0,
        "blockQuotes": 0,
        "lists": 1,
        "listItems": 3,
        "tables": 0,
        "links": 0,
        "thematicBreaks": 0,
        "warnings": []
      },
      "operation": "emit"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "emit", vector, False, _SEAM)


async def test_vector_8_quilldown_emit_ordered_start_emit():
    vector_json = r"""
    {
      "name": "ordered_start-emit",
      "stage": "callable",
      "input": {
        "doc": {
          "blocks": [
            {
              "items": [
                {
                  "kind": "list_item",
                  "blocks": [
                    {
                      "content": [
                        {
                          "data": "first",
                          "kind": "text"
                        }
                      ],
                      "kind": "paragraph"
                    }
                  ]
                },
                {
                  "kind": "list_item",
                  "blocks": [
                    {
                      "content": [
                        {
                          "data": "second",
                          "kind": "text"
                        }
                      ],
                      "kind": "paragraph"
                    }
                  ]
                }
              ],
              "kind": "list",
              "ordered": true,
              "start": 3
            }
          ]
        }
      },
      "expected": {
        "headings": 0,
        "paragraphs": 2,
        "codeBlocks": 0,
        "blockQuotes": 0,
        "lists": 1,
        "listItems": 2,
        "tables": 0,
        "links": 0,
        "thematicBreaks": 0,
        "warnings": []
      },
      "operation": "emit"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "emit", vector, False, _SEAM)


async def test_vector_9_quilldown_emit_paragraph_inline_emit():
    vector_json = r"""
    {
      "name": "paragraph_inline-emit",
      "stage": "callable",
      "input": {
        "doc": {
          "blocks": [
            {
              "content": [
                {
                  "data": "This is ",
                  "kind": "text"
                },
                {
                  "data": [
                    {
                      "data": "bold",
                      "kind": "text"
                    }
                  ],
                  "kind": "strong"
                },
                {
                  "data": ", ",
                  "kind": "text"
                },
                {
                  "data": [
                    {
                      "data": "italic",
                      "kind": "text"
                    }
                  ],
                  "kind": "emphasis"
                },
                {
                  "data": ", ",
                  "kind": "text"
                },
                {
                  "data": [
                    {
                      "data": "struck",
                      "kind": "text"
                    }
                  ],
                  "kind": "strikethrough"
                },
                {
                  "data": ", and ",
                  "kind": "text"
                },
                {
                  "data": "code",
                  "kind": "code"
                },
                {
                  "data": ".",
                  "kind": "text"
                }
              ],
              "kind": "paragraph"
            }
          ]
        }
      },
      "expected": {
        "headings": 0,
        "paragraphs": 1,
        "codeBlocks": 0,
        "blockQuotes": 0,
        "lists": 0,
        "listItems": 0,
        "tables": 0,
        "links": 0,
        "thematicBreaks": 0,
        "warnings": []
      },
      "operation": "emit"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "emit", vector, False, _SEAM)


async def test_vector_10_quilldown_emit_table_emit():
    vector_json = r"""
    {
      "name": "table-emit",
      "stage": "callable",
      "input": {
        "doc": {
          "blocks": [
            {
              "align": [
                "left",
                "right"
              ],
              "head": {
                "cells": [
                  {
                    "content": [
                      {
                        "data": "Name",
                        "kind": "text"
                      }
                    ]
                  },
                  {
                    "content": [
                      {
                        "data": "Qty",
                        "kind": "text"
                      }
                    ]
                  }
                ]
              },
              "kind": "table",
              "rows": [
                {
                  "cells": [
                    {
                      "content": [
                        {
                          "data": "Pears",
                          "kind": "text"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "data": "3",
                          "kind": "text"
                        }
                      ]
                    }
                  ]
                },
                {
                  "cells": [
                    {
                      "content": [
                        {
                          "data": "Figs",
                          "kind": "text"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "data": "12",
                          "kind": "text"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      },
      "expected": {
        "headings": 0,
        "paragraphs": 0,
        "codeBlocks": 0,
        "blockQuotes": 0,
        "lists": 0,
        "listItems": 0,
        "tables": 1,
        "links": 0,
        "thematicBreaks": 0,
        "warnings": []
      },
      "operation": "emit"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "emit", vector, False, _SEAM)


async def test_vector_11_quilldown_emit_task_list_emit():
    vector_json = r"""
    {
      "name": "task_list-emit",
      "stage": "callable",
      "input": {
        "doc": {
          "blocks": [
            {
              "items": [
                {
                  "kind": "list_item",
                  "blocks": [
                    {
                      "content": [
                        {
                          "data": "done",
                          "kind": "text"
                        }
                      ],
                      "kind": "paragraph"
                    }
                  ],
                  "task": true
                },
                {
                  "kind": "list_item",
                  "blocks": [
                    {
                      "content": [
                        {
                          "data": "todo",
                          "kind": "text"
                        }
                      ],
                      "kind": "paragraph"
                    }
                  ],
                  "task": false
                }
              ],
              "kind": "list",
              "ordered": false,
              "start": 1
            }
          ]
        }
      },
      "expected": {
        "headings": 0,
        "paragraphs": 2,
        "codeBlocks": 0,
        "blockQuotes": 0,
        "lists": 1,
        "listItems": 2,
        "tables": 0,
        "links": 0,
        "thematicBreaks": 0,
        "warnings": []
      },
      "operation": "emit"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "emit", vector, False, _SEAM)


async def test_vector_12_quilldown_emit_thematic_break_emit():
    vector_json = r"""
    {
      "name": "thematic_break-emit",
      "stage": "callable",
      "input": {
        "doc": {
          "blocks": [
            {
              "content": [
                {
                  "data": "before",
                  "kind": "text"
                }
              ],
              "kind": "paragraph"
            },
            {
              "kind": "thematic_break"
            },
            {
              "content": [
                {
                  "data": "after",
                  "kind": "text"
                }
              ],
              "kind": "paragraph"
            }
          ]
        }
      },
      "expected": {
        "headings": 0,
        "paragraphs": 2,
        "codeBlocks": 0,
        "blockQuotes": 0,
        "lists": 0,
        "listItems": 0,
        "tables": 0,
        "links": 0,
        "thematicBreaks": 1,
        "warnings": []
      },
      "operation": "emit"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "emit", vector, False, _SEAM)


async def test_vector_13_quilldown_lower_alert_note_unwrap_lower():
    vector_json = r"""
    {
      "name": "alert_note_unwrap-lower",
      "stage": "callable",
      "input": {
        "markdown": "> [!NOTE]\n> This is a note.\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "This is a note.",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_14_quilldown_lower_alert_title_dropped_lower():
    vector_json = r"""
    {
      "name": "alert_title_dropped-lower",
      "stage": "callable",
      "input": {
        "markdown": "> [!TIP] a title here\n> body text\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "body text",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_15_quilldown_lower_alert_unknown_kept_lower():
    vector_json = r"""
    {
      "name": "alert_unknown_kept-lower",
      "stage": "callable",
      "input": {
        "markdown": "> [!UNKNOWN]\n> body\n"
      },
      "expected": {
        "blocks": [
          {
            "blocks": [
              {
                "content": [
                  {
                    "data": "[!UNKNOWN]",
                    "kind": "text"
                  },
                  {
                    "kind": "soft_break"
                  },
                  {
                    "data": "body",
                    "kind": "text"
                  }
                ],
                "kind": "paragraph"
              }
            ],
            "kind": "block_quote"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_16_quilldown_lower_anchor_link_lower():
    vector_json = r"""
    {
      "name": "anchor_link-lower",
      "stage": "callable",
      "input": {
        "markdown": "# Getting Started\n\nJump to [start](#getting-started).\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "Getting Started",
                "kind": "text"
              }
            ],
            "kind": "heading",
            "level": 1
          },
          {
            "content": [
              {
                "data": "Jump to ",
                "kind": "text"
              },
              {
                "kind": "link",
                "href": "#getting-started",
                "content": [
                  {
                    "data": "start",
                    "kind": "text"
                  }
                ]
              },
              {
                "data": ".",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_17_quilldown_lower_autolink_bracket_suppressed_lower():
    vector_json = r"""
    {
      "name": "autolink_bracket_suppressed-lower",
      "stage": "callable",
      "input": {
        "markdown": "[**x** https://example.com]\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "[",
                "kind": "text"
              },
              {
                "data": [
                  {
                    "data": "x",
                    "kind": "text"
                  }
                ],
                "kind": "strong"
              },
              {
                "data": " https://example.com]",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_18_quilldown_lower_autolink_domain_reject_lower():
    vector_json = r"""
    {
      "name": "autolink_domain_reject-lower",
      "stage": "callable",
      "input": {
        "markdown": "http://a.b_c.com\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "http://a.b_c.com",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_19_quilldown_lower_autolink_email_lower():
    vector_json = r"""
    {
      "name": "autolink_email-lower",
      "stage": "callable",
      "input": {
        "markdown": "Mail a.b+tag@example.co.uk.\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "Mail ",
                "kind": "text"
              },
              {
                "content": [
                  {
                    "data": "a.b+tag@example.co.uk",
                    "kind": "text"
                  }
                ],
                "href": "mailto:a.b+tag@example.co.uk",
                "kind": "link"
              },
              {
                "data": ".",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_20_quilldown_lower_autolink_footnote_preceder_lower():
    vector_json = r"""
    {
      "name": "autolink_footnote_preceder-lower",
      "stage": "callable",
      "input": {
        "markdown": "*x*[^1]www.y.com\n\n[^1]: note\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": [
                  {
                    "data": "x",
                    "kind": "text"
                  }
                ],
                "kind": "emphasis"
              },
              {
                "data": "www.y.com",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_21_quilldown_lower_autolink_url_parens_lower():
    vector_json = r"""
    {
      "name": "autolink_url_parens-lower",
      "stage": "callable",
      "input": {
        "markdown": "Visit https://example.com/a_(b).\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "Visit ",
                "kind": "text"
              },
              {
                "content": [
                  {
                    "data": "https://example.com/a_(b)",
                    "kind": "text"
                  }
                ],
                "href": "https://example.com/a_(b)",
                "kind": "link"
              },
              {
                "data": ".",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_22_quilldown_lower_autolink_www_preceder_lower():
    vector_json = r"""
    {
      "name": "autolink_www_preceder-lower",
      "stage": "callable",
      "input": {
        "markdown": "`x`www.example.com\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "x",
                "kind": "code"
              },
              {
                "data": "www.example.com",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_23_quilldown_lower_autolink_www_lower():
    vector_json = r"""
    {
      "name": "autolink_www-lower",
      "stage": "callable",
      "input": {
        "markdown": "See www.example.com/path\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "See ",
                "kind": "text"
              },
              {
                "content": [
                  {
                    "data": "www.example.com/path",
                    "kind": "text"
                  }
                ],
                "href": "http://www.example.com/path",
                "kind": "link"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_24_quilldown_lower_blockquote_lower():
    vector_json = r"""
    {
      "name": "blockquote-lower",
      "stage": "callable",
      "input": {
        "markdown": "> quoted **text**\n"
      },
      "expected": {
        "blocks": [
          {
            "blocks": [
              {
                "content": [
                  {
                    "data": "quoted ",
                    "kind": "text"
                  },
                  {
                    "data": [
                      {
                        "data": "text",
                        "kind": "text"
                      }
                    ],
                    "kind": "strong"
                  }
                ],
                "kind": "paragraph"
              }
            ],
            "kind": "block_quote"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_25_quilldown_lower_bullet_list_lower():
    vector_json = r"""
    {
      "name": "bullet_list-lower",
      "stage": "callable",
      "input": {
        "markdown": "- alpha\n- beta\n"
      },
      "expected": {
        "blocks": [
          {
            "items": [
              {
                "kind": "list_item",
                "blocks": [
                  {
                    "content": [
                      {
                        "data": "alpha",
                        "kind": "text"
                      }
                    ],
                    "kind": "paragraph"
                  }
                ]
              },
              {
                "kind": "list_item",
                "blocks": [
                  {
                    "content": [
                      {
                        "data": "beta",
                        "kind": "text"
                      }
                    ],
                    "kind": "paragraph"
                  }
                ]
              }
            ],
            "kind": "list",
            "ordered": false,
            "start": 1
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_26_quilldown_lower_code_block_lower():
    vector_json = r"""
    {
      "name": "code_block-lower",
      "stage": "callable",
      "input": {
        "markdown": "```rust\nfn main() {}\n```\n"
      },
      "expected": {
        "blocks": [
          {
            "code": "fn main() {}\n",
            "kind": "code_block",
            "language": "rust"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_27_quilldown_lower_display_math_lower():
    vector_json = r"""
    {
      "name": "display_math-lower",
      "stage": "callable",
      "input": {
        "markdown": "Before\n\n$$\na+b\n$$\n\nAfter\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "Before",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          },
          {
            "content": [
              {
                "data": "\na+b\n",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          },
          {
            "content": [
              {
                "data": "After",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_28_quilldown_lower_external_link_lower():
    vector_json = r"""
    {
      "name": "external_link-lower",
      "stage": "callable",
      "input": {
        "markdown": "See the [manual](https://example.com/guide).\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "See the ",
                "kind": "text"
              },
              {
                "kind": "link",
                "href": "https://example.com/guide",
                "content": [
                  {
                    "data": "manual",
                    "kind": "text"
                  }
                ]
              },
              {
                "data": ".",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_29_quilldown_lower_footnote_case_fold_lower():
    vector_json = r"""
    {
      "name": "footnote_case_fold-lower",
      "stage": "callable",
      "input": {
        "markdown": "text[^A] end\n\n[^a]: note\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "text",
                "kind": "text"
              },
              {
                "data": " end",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_30_quilldown_lower_footnote_inline_lower():
    vector_json = r"""
    {
      "name": "footnote_inline-lower",
      "stage": "callable",
      "input": {
        "markdown": "text^[inline note] end\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "text^[inline note] end",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_31_quilldown_lower_footnote_ref_lower():
    vector_json = r"""
    {
      "name": "footnote_ref-lower",
      "stage": "callable",
      "input": {
        "markdown": "text[^1] end\n\n[^1]: note\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "text",
                "kind": "text"
              },
              {
                "data": " end",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_32_quilldown_lower_heading_para_lower():
    vector_json = r"""
    {
      "name": "heading_para-lower",
      "stage": "callable",
      "input": {
        "markdown": "# Title\n\nHello **world**.\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "Title",
                "kind": "text"
              }
            ],
            "kind": "heading",
            "level": 1
          },
          {
            "content": [
              {
                "data": "Hello ",
                "kind": "text"
              },
              {
                "data": [
                  {
                    "data": "world",
                    "kind": "text"
                  }
                ],
                "kind": "strong"
              },
              {
                "data": ".",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_33_quilldown_lower_headings_lower():
    vector_json = r"""
    {
      "name": "headings-lower",
      "stage": "callable",
      "input": {
        "markdown": "# One\n\n## Two\n\n### Three\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "One",
                "kind": "text"
              }
            ],
            "kind": "heading",
            "level": 1
          },
          {
            "content": [
              {
                "data": "Two",
                "kind": "text"
              }
            ],
            "kind": "heading",
            "level": 2
          },
          {
            "content": [
              {
                "data": "Three",
                "kind": "text"
              }
            ],
            "kind": "heading",
            "level": 3
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_34_quilldown_lower_image_alt_lower():
    vector_json = r"""
    {
      "name": "image_alt-lower",
      "stage": "callable",
      "input": {
        "markdown": "See ![a cat](cat.png) here.\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "See ",
                "kind": "text"
              },
              {
                "data": "a cat",
                "kind": "text"
              },
              {
                "data": " here.",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_35_quilldown_lower_inline_math_lower():
    vector_json = r"""
    {
      "name": "inline_math-lower",
      "stage": "callable",
      "input": {
        "markdown": "Euler: $E = mc^2$ ok.\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "Euler: ",
                "kind": "text"
              },
              {
                "data": "E = mc^2",
                "kind": "text"
              },
              {
                "data": " ok.",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_36_quilldown_lower_math_code_lower():
    vector_json = r"""
    {
      "name": "math_code-lower",
      "stage": "callable",
      "input": {
        "markdown": "Euler is $`e^{i\\pi}+1=0`$ done.\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "Euler is ",
                "kind": "text"
              },
              {
                "data": "e^{i\\pi}+1=0",
                "kind": "text"
              },
              {
                "data": " done.",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_37_quilldown_lower_math_currency_lower():
    vector_json = r"""
    {
      "name": "math_currency-lower",
      "stage": "callable",
      "input": {
        "markdown": "I paid $100 and $200 today.\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "I paid $100 and $200 today.",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_38_quilldown_lower_math_digit_after_close_lower():
    vector_json = r"""
    {
      "name": "math_digit_after_close-lower",
      "stage": "callable",
      "input": {
        "markdown": "x$a$2\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "x$a$2",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_39_quilldown_lower_math_space_boundary_lower():
    vector_json = r"""
    {
      "name": "math_space_boundary-lower",
      "stage": "callable",
      "input": {
        "markdown": "$ x $\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "$ x $",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_40_quilldown_lower_ordered_list_lower():
    vector_json = r"""
    {
      "name": "ordered_list-lower",
      "stage": "callable",
      "input": {
        "markdown": "1. alpha\n2. beta\n3. gamma\n"
      },
      "expected": {
        "blocks": [
          {
            "items": [
              {
                "kind": "list_item",
                "blocks": [
                  {
                    "content": [
                      {
                        "data": "alpha",
                        "kind": "text"
                      }
                    ],
                    "kind": "paragraph"
                  }
                ]
              },
              {
                "kind": "list_item",
                "blocks": [
                  {
                    "content": [
                      {
                        "data": "beta",
                        "kind": "text"
                      }
                    ],
                    "kind": "paragraph"
                  }
                ]
              },
              {
                "kind": "list_item",
                "blocks": [
                  {
                    "content": [
                      {
                        "data": "gamma",
                        "kind": "text"
                      }
                    ],
                    "kind": "paragraph"
                  }
                ]
              }
            ],
            "kind": "list",
            "ordered": true,
            "start": 1
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_41_quilldown_lower_ordered_start_lower():
    vector_json = r"""
    {
      "name": "ordered_start-lower",
      "stage": "callable",
      "input": {
        "markdown": "3. first\n4. second\n"
      },
      "expected": {
        "blocks": [
          {
            "items": [
              {
                "kind": "list_item",
                "blocks": [
                  {
                    "content": [
                      {
                        "data": "first",
                        "kind": "text"
                      }
                    ],
                    "kind": "paragraph"
                  }
                ]
              },
              {
                "kind": "list_item",
                "blocks": [
                  {
                    "content": [
                      {
                        "data": "second",
                        "kind": "text"
                      }
                    ],
                    "kind": "paragraph"
                  }
                ]
              }
            ],
            "kind": "list",
            "ordered": true,
            "start": 3
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_42_quilldown_lower_paragraph_inline_lower():
    vector_json = r"""
    {
      "name": "paragraph_inline-lower",
      "stage": "callable",
      "input": {
        "markdown": "This is **bold**, *italic*, ~~struck~~, and `code`.\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "This is ",
                "kind": "text"
              },
              {
                "data": [
                  {
                    "data": "bold",
                    "kind": "text"
                  }
                ],
                "kind": "strong"
              },
              {
                "data": ", ",
                "kind": "text"
              },
              {
                "data": [
                  {
                    "data": "italic",
                    "kind": "text"
                  }
                ],
                "kind": "emphasis"
              },
              {
                "data": ", ",
                "kind": "text"
              },
              {
                "data": [
                  {
                    "data": "struck",
                    "kind": "text"
                  }
                ],
                "kind": "strikethrough"
              },
              {
                "data": ", and ",
                "kind": "text"
              },
              {
                "data": "code",
                "kind": "code"
              },
              {
                "data": ".",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_43_quilldown_lower_subscript_in_strikethrough_lower():
    vector_json = r"""
    {
      "name": "subscript_in_strikethrough-lower",
      "stage": "callable",
      "input": {
        "markdown": "~~H~2~O~~\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": [
                  {
                    "data": "H",
                    "kind": "text"
                  },
                  {
                    "data": "2",
                    "kind": "text"
                  },
                  {
                    "data": "O",
                    "kind": "text"
                  }
                ],
                "kind": "strikethrough"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_44_quilldown_lower_subscript_mismatch_literal_lower():
    vector_json = r"""
    {
      "name": "subscript_mismatch_literal-lower",
      "stage": "callable",
      "input": {
        "markdown": "~~a~b!~d~~\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "~~a~b!~d~~",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_45_quilldown_lower_subscript_punct_bypass_lower():
    vector_json = r"""
    {
      "name": "subscript_punct_bypass-lower",
      "stage": "callable",
      "input": {
        "markdown": "x~-1~\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "x",
                "kind": "text"
              },
              {
                "data": "-1",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_46_quilldown_lower_subscript_lower():
    vector_json = r"""
    {
      "name": "subscript-lower",
      "stage": "callable",
      "input": {
        "markdown": "H~2~O\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "H",
                "kind": "text"
              },
              {
                "data": "2",
                "kind": "text"
              },
              {
                "data": "O",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_47_quilldown_lower_superscript_emphasis_lower():
    vector_json = r"""
    {
      "name": "superscript_emphasis-lower",
      "stage": "callable",
      "input": {
        "markdown": "x^*y*^\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "x",
                "kind": "text"
              },
              {
                "data": [
                  {
                    "data": "y",
                    "kind": "text"
                  }
                ],
                "kind": "emphasis"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_48_quilldown_lower_superscript_image_alt_lower():
    vector_json = r"""
    {
      "name": "superscript_image_alt-lower",
      "stage": "callable",
      "input": {
        "markdown": "![a^b^](u.png)\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "a^b^",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_49_quilldown_lower_superscript_in_strong_lower():
    vector_json = r"""
    {
      "name": "superscript_in_strong-lower",
      "stage": "callable",
      "input": {
        "markdown": "A **bold x^2^** term\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "A ",
                "kind": "text"
              },
              {
                "data": [
                  {
                    "data": "bold x",
                    "kind": "text"
                  },
                  {
                    "data": "2",
                    "kind": "text"
                  }
                ],
                "kind": "strong"
              },
              {
                "data": " term",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_50_quilldown_lower_superscript_link_label_lower():
    vector_json = r"""
    {
      "name": "superscript_link_label-lower",
      "stage": "callable",
      "input": {
        "markdown": "[note^2^](http://example.com)\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "content": [
                  {
                    "data": "note^2^",
                    "kind": "text"
                  }
                ],
                "href": "http://example.com",
                "kind": "link"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_51_quilldown_lower_superscript_lower():
    vector_json = r"""
    {
      "name": "superscript-lower",
      "stage": "callable",
      "input": {
        "markdown": "area r^2^ end\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "area r",
                "kind": "text"
              },
              {
                "data": "2",
                "kind": "text"
              },
              {
                "data": " end",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_52_quilldown_lower_table_lower():
    vector_json = r"""
    {
      "name": "table-lower",
      "stage": "callable",
      "input": {
        "markdown": "| Name | Qty |\n|:-----|----:|\n| Pears | 3 |\n| Figs | 12 |\n"
      },
      "expected": {
        "blocks": [
          {
            "align": [
              "left",
              "right"
            ],
            "head": {
              "cells": [
                {
                  "content": [
                    {
                      "data": "Name",
                      "kind": "text"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "data": "Qty",
                      "kind": "text"
                    }
                  ]
                }
              ]
            },
            "kind": "table",
            "rows": [
              {
                "cells": [
                  {
                    "content": [
                      {
                        "data": "Pears",
                        "kind": "text"
                      }
                    ]
                  },
                  {
                    "content": [
                      {
                        "data": "3",
                        "kind": "text"
                      }
                    ]
                  }
                ]
              },
              {
                "cells": [
                  {
                    "content": [
                      {
                        "data": "Figs",
                        "kind": "text"
                      }
                    ]
                  },
                  {
                    "content": [
                      {
                        "data": "12",
                        "kind": "text"
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_53_quilldown_lower_task_list_lower():
    vector_json = r"""
    {
      "name": "task_list-lower",
      "stage": "callable",
      "input": {
        "markdown": "- [x] done\n- [ ] todo\n"
      },
      "expected": {
        "blocks": [
          {
            "items": [
              {
                "kind": "list_item",
                "blocks": [
                  {
                    "content": [
                      {
                        "data": "done",
                        "kind": "text"
                      }
                    ],
                    "kind": "paragraph"
                  }
                ],
                "task": true
              },
              {
                "kind": "list_item",
                "blocks": [
                  {
                    "content": [
                      {
                        "data": "todo",
                        "kind": "text"
                      }
                    ],
                    "kind": "paragraph"
                  }
                ],
                "task": false
              }
            ],
            "kind": "list",
            "ordered": false,
            "start": 1
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)


async def test_vector_54_quilldown_lower_thematic_break_lower():
    vector_json = r"""
    {
      "name": "thematic_break-lower",
      "stage": "callable",
      "input": {
        "markdown": "before\n\n---\n\nafter\n"
      },
      "expected": {
        "blocks": [
          {
            "content": [
              {
                "data": "before",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          },
          {
            "kind": "thematic_break"
          },
          {
            "content": [
              {
                "data": "after",
                "kind": "text"
              }
            ],
            "kind": "paragraph"
          }
        ]
      },
      "operation": "lower"
    }
    """
    vector = json.loads(vector_json, strict=False)
    await run_vector("Quilldown", "lower", vector, False, _SEAM)
