# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import FootnoteDefinition


def test_load_json_footnotedefinition():
    json_data = r"""
    {
      "label": "sample",
      "blocks": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = FootnoteDefinition.load(data)
    assert instance is not None
    assert instance.label == "sample"


def test_load_yaml_footnotedefinition():
    yaml_data = r"""
    label: sample
    blocks: []

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = FootnoteDefinition.load(data)
    assert instance is not None
    assert instance.label == "sample"


def test_roundtrip_json_footnotedefinition():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "label": "sample",
      "blocks": []
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = FootnoteDefinition.load(original_data)
    saved_data = instance.save()
    reloaded = FootnoteDefinition.load(saved_data)
    assert reloaded is not None
    assert reloaded.label == "sample"


def test_to_json_footnotedefinition():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "label": "sample",
      "blocks": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = FootnoteDefinition.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_footnotedefinition():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "label": "sample",
      "blocks": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = FootnoteDefinition.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
