# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import ImageInline


def test_load_json_imageinline():
    json_data = r"""
    {
      "kind": "image",
      "src": "sample",
      "alt": "sample",
      "title": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ImageInline.load(data)
    assert instance is not None
    assert instance.kind == "image"
    assert instance.src == "sample"
    assert instance.alt == "sample"
    assert instance.title == "sample"


def test_load_yaml_imageinline():
    yaml_data = r"""
    kind: image
    src: sample
    alt: sample
    title: sample

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = ImageInline.load(data)
    assert instance is not None
    assert instance.kind == "image"
    assert instance.src == "sample"
    assert instance.alt == "sample"
    assert instance.title == "sample"


def test_roundtrip_json_imageinline():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "kind": "image",
      "src": "sample",
      "alt": "sample",
      "title": "sample"
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = ImageInline.load(original_data)
    saved_data = instance.save()
    reloaded = ImageInline.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "image"
    assert reloaded.src == "sample"
    assert reloaded.alt == "sample"
    assert reloaded.title == "sample"


def test_to_json_imageinline():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "kind": "image",
      "src": "sample",
      "alt": "sample",
      "title": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ImageInline.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_imageinline():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "kind": "image",
      "src": "sample",
      "alt": "sample",
      "title": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ImageInline.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
