# <auto-generated by typra-emitter>
import json

import yaml

from quilldown_spec import AlertBlock


def test_load_json_alertblock():
    json_data = r"""
    {
      "kind": "alert",
      "alert_type": "sample",
      "blocks": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = AlertBlock.load(data)
    assert instance is not None
    assert instance.kind == "alert"
    assert instance.alert_type == "sample"


def test_load_yaml_alertblock():
    yaml_data = r"""
    kind: alert
    alert_type: sample
    blocks: []

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = AlertBlock.load(data)
    assert instance is not None
    assert instance.kind == "alert"
    assert instance.alert_type == "sample"


def test_roundtrip_json_alertblock():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "kind": "alert",
      "alert_type": "sample",
      "blocks": []
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = AlertBlock.load(original_data)
    saved_data = instance.save()
    reloaded = AlertBlock.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "alert"
    assert reloaded.alert_type == "sample"


def test_to_json_alertblock():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "kind": "alert",
      "alert_type": "sample",
      "blocks": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = AlertBlock.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_alertblock():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "kind": "alert",
      "alert_type": "sample",
      "blocks": []
    }
    """
    data = json.loads(json_data, strict=False)
    instance = AlertBlock.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
