# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import TextInline


def test_load_json_textinline():
    json_data = r"""
    {
      "kind": "text",
      "data": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = TextInline.load(data)
    assert instance is not None
    assert instance.kind == "text"
    assert instance.data == "sample"


def test_load_yaml_textinline():
    yaml_data = r"""
    kind: text
    data: sample

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = TextInline.load(data)
    assert instance is not None
    assert instance.kind == "text"
    assert instance.data == "sample"


def test_roundtrip_json_textinline():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "kind": "text",
      "data": "sample"
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = TextInline.load(original_data)
    saved_data = instance.save()
    reloaded = TextInline.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "text"
    assert reloaded.data == "sample"


def test_to_json_textinline():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "kind": "text",
      "data": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = TextInline.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_textinline():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "kind": "text",
      "data": "sample"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = TextInline.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
