# <auto-generated by typra-emitter>
import json
import yaml

from quilldown_spec import ThematicBreak


def test_load_json_thematicbreak():
    json_data = r"""
    {
      "kind": "thematic_break"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ThematicBreak.load(data)
    assert instance is not None
    assert instance.kind == "thematic_break"


def test_load_yaml_thematicbreak():
    yaml_data = r"""
    kind: thematic_break

    """
    data = yaml.load(yaml_data, Loader=yaml.FullLoader)
    instance = ThematicBreak.load(data)
    assert instance is not None
    assert instance.kind == "thematic_break"


def test_roundtrip_json_thematicbreak():
    """Test that load -> save -> load produces equivalent data."""
    json_data = r"""
    {
      "kind": "thematic_break"
    }
    """
    original_data = json.loads(json_data, strict=False)
    instance = ThematicBreak.load(original_data)
    saved_data = instance.save()
    reloaded = ThematicBreak.load(saved_data)
    assert reloaded is not None
    assert reloaded.kind == "thematic_break"


def test_to_json_thematicbreak():
    """Test that to_json produces valid JSON."""
    json_data = r"""
    {
      "kind": "thematic_break"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ThematicBreak.load(data)
    json_output = instance.to_json()
    assert json_output is not None
    parsed = json.loads(json_output)
    assert isinstance(parsed, dict)


def test_to_yaml_thematicbreak():
    """Test that to_yaml produces valid YAML."""
    json_data = r"""
    {
      "kind": "thematic_break"
    }
    """
    data = json.loads(json_data, strict=False)
    instance = ThematicBreak.load(data)
    yaml_output = instance.to_yaml()
    assert yaml_output is not None
    parsed = yaml.safe_load(yaml_output)
    assert isinstance(parsed, dict)
